#!/usr/bin/env python

import sys

#import rospy
from rqt_gui.main import Main
#from python_qt_binding.QtGui import QApplication

#def finish(*arg):
#  '''
#  Callback called on exit of the ros node.
#  '''
#  QApplication.exit(0)

main = Main()
#rospy.on_shutdown(finish) #handle the ROS shutdown commands
sys.exit(main.main(sys.argv, standalone='fkie_iop_rqt_velocity'))

