// *****************************************************************************
//
// Author: Alexander Tiderko
// Copyright 2022 Fraunhofer FKIE
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Based on the mapviz plugin of
// Copyright (c) 2014, Southwest Research Institute® (SwRI®)
// All rights reserved.
//
// *****************************************************************************

#ifndef FKIE_IOP_MAPVIZ_PLUGINS_ACCESS_CONTROL_DIALOG_H_
#define FKIE_IOP_MAPVIZ_PLUGINS_ACCESS_CONTROL_DIALOG_H_

// C++ standard libraries
#include <map>
#include <string>
#include <vector>

// QT libraries
#include <QCloseEvent>
#include <QDialog>

// ROS libraries
#include <ros/ros.h>

// Other Plugin-Files
#include "access_control_robot.h"

// QT autogenerated files
#include "ui_access_control_dialog.h"
#include "ui_access_control_robot.h"

namespace fkie_iop_mapviz_plugins
{
  class AccessControlDialog : public QDialog
  {
   Q_OBJECT

   public:

    AccessControlDialog(const std::vector<AccessControlRobot *> robotlist);
    virtual ~AccessControlDialog();

    /**
     * @brief: Insert the robot widgets into the dialog layout. They will not be deleted when the dialog is closed.
     * 
     * @param robotlist: list with available robots
     **/
    void update(const std::vector<AccessControlRobot *> robotlist);

   protected:
    void closeEvent(QCloseEvent *e) override;

   private:
    Ui::DialogAccessControl ui_;
    /**
     * @brief: remove items w/o delete robot widgets. They are stored as robot objects.
     **/
    void removeRobotWidgets();
  };
}

#endif  // FKIE_IOP_MAPVIZ_PLUGINS_ACCESS_CONTROL_DIALOG_H_
